

set( CMAKE_CXX_FLAGS_MASTER ${CMAKE_CXX_FLAGS_RELEASE} )
set( CMAKE_EXE_LINKER_FLAGS_MASTER ${CMAKE_EXE_LINKER_FLAGS_RELEASE} )

set( TIKI_WINDOWS True )

set( TIKI_RENDER_OPENGL True )
set( TIKI_USE_SDL2 True )


